### ISSUE TITLE
раздел про статические генераторы

### ISSUE THREAD

**Issue by epogrebnyak** [emacsway/dckms-template#1]
Сейчас в "Другие интересные проекты" упомянуты и крупные мейнстримовые генераторы сацтов по 40 тыс звездочек на гитхабе:

    https://gohugo.io/ (поддерживает Markdown, reStructuredText, Org-mode, etc.)
    https://github.com/google/docsy
    https://github.com/jekyll/jekyll

и небольшие нишевые тулзы. У меня предложение сделать раздел "статические генераторы сайтов", там упомянуть:

- hugo
- jekyll
- семейство js генераторов 
- mkdocs
- jupyterbook (использует myst parser)
- pelican
- возможно какие-то другие 

У меня был список таких генераторов, могу его обновить с рейтингами на гитхабе.  

Могу сделать pr к ридме.

**Comment by emacsway** [comment]
Спасибо) Я был бы признателен.
